spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Allows using /**/... path in FrontendController

server:
  port: 24003

socket-io:
  port: 48207