GET https://mamyklocga.przemyslawpitus.pl:48207/socket.io/?EIO=3&transport=polling&t=1686237611232-1&sid=2c522855-3b2e-476e-8ed5-e7e04801da54

### Hello
POST http://localhost:24003/api/me/hello
Content-Type: application/json
Accept: application/json

{
  "sessionId": "ce8f37ed-1589-4ac5-8d85-74891c8131d7"
}

### Set username
POST http://localhost:24003/api/me/username
Content-Type: application/json
Accept: application/json
Cookie: userId=e2ee15f9-cdd0-4dfd-bfa3-5c8abbd8bf0b

{
  "username": "deko"
}

### Create room
POST http://localhost:24003/api/rooms
Content-Type: application/json
Accept: application/json
Cookie: userId=e2ee15f9-cdd0-4dfd-bfa3-5c8abbd8bf0b

{
  "roomName": "nasszwa"
}

> {% client.global.set("roomCode", response.body.code) %}

### Join room
POST http://localhost:24003/api/rooms/{{roomCode}}/join
Content-Type: application/json
Accept: application/json
Cookie: userId=e2ee15f9-cdd0-4dfd-bfa3-5c8abbd8bf0b

### Start game
POST http://localhost:24003/api/rooms/{{roomCode}}/start
Content-Type: application/json
Accept: application/json
Cookie: userId=e2ee15f9-cdd0-4dfd-bfa3-5c8abbd8bf0b

### Get rooms
GET http://localhost:24003/api/rooms
Content-Type: application/json
Accept: application/json

### Get room
GET http://localhost:24003/api/rooms/{{roomCode}}
Content-Type: application/json
Accept: application/json
Cookie: userId=e2ee15f9-cdd0-4dfd-bfa3-5c8abbd8bf0b### Get room

### Start current round
POST http://localhost:24003/api/rooms/2918/startRound
Content-Type: application/json
Accept: application/json
Cookie: userId=e072cdb1-2780-4676-a4c2-731b4e172e57

### Watch room (long polling)
GET http://localhost:24003/api/rooms/2323/watch
Content-Type: application/json
Accept: application/json
Cookie: userId=e2ee15f9-cdd0-4dfd-bfa3-5c8abbd8bf0b

### Watch rooms (long polling)
GET http://localhost:24003/api/rooms/watch
Content-Type: application/json
Accept: application/json
Cookie: userId=e2ee15f9-cdd0-4dfd-bfa3-5c8abbd8bf0b