GET https://mamyklocga.przemyslawpitus.pl:48207/socket.io/?EIO=3&transport=polling&t=1686237611232-1&sid=2c522855-3b2e-476e-8ed5-e7e04801da54

### Hello
POST http://localhost:24003/api/users/hello
Content-Type: application/json
Accept: application/json

{
  "sessionId": "d06bc845-350a-411d-a778-e9cc51442095"
}

### Create room
POST http://localhost:24003/api/rooms
Content-Type: application/json
Accept: application/json
Cookie: userId=862f5a34-4e9c-4ac0-833e-f516a10adef3

{
  "roomName": "nazwa",
  "username": "Deko"
}

> {% client.global.set("roomId", response.body.roomId) %}

### Join room
POST http://localhost:24003/api/rooms/{{roomId}}/join
Content-Type: application/json
Accept: application/json
Cookie: userId=35f31eac-6b84-4192-9293-eda6820bbd03

{
  "username": "gram"
}

### Start game
POST http://localhost:24003/api/rooms/{{roomId}}/start
Content-Type: application/json
Accept: application/json
Cookie: userId=862f5a34-4e9c-4ac0-833e-f516a10adef3

