package pl.przemyslawpitus.mamyklocga.domain.game.startGameUseCase

val rawWords = listOf(
    "Wodody (Toy Story)",
    "Buzz Astral (Toy Story)",
    "Chewbacca",
    "R2-D2",
    "Batman",
    "Kot w butach",
    "Superman",
    "Tom i Jerry",
    "Lord Farquaad",
    "Myszka Miki",
    "Fineasz (Fineasz i Ferb)",
    "Ferb (Fineasz i Ferb)",
    "Pepe Pan Dziobak",
    "Spongebob",
    "Magnes",
    "Joker",
    "Kapitan Jack Sparrow",
    "Buka",
    "Muminek",
    "Atomówki",
    "Skalmar (Spongebob)",
    "Patryk (Spongebob)",
    "Mario",
    "Kubuś puchatek",
    "Prosiaczek",
    "Sygnalizacja świetlna",
    "Święty Mikołaj",
    "Papież",
    "Harry Potter",
    "Hulk",
    "Gandalf",
    "Yoda",
    "Darth Vader",
    "Indiana Jones",
    "Shrek",
    "Garfield",
    "Mike Wazowski",
    "Nemo",
    "Kaczor Donald",
    "Scooby Doo",
    "Kermit",
    "Goofy",
    "Różowa Pantera",
    "Sonic",
    "Luigi",
    "Pikachu",
    "Pac-Man",
    "Krecik",
    "Czerwony Kapturek",
    "Kapitan Hak",
    "Piotruś Pan",
    "Hobbit",
    "Homer Simpson",
    "Marge Simpson",
    "Mionionek",
    "Smerf",
    "Gargamel",
    "Wieża Eiffla",
    "Skarpetka",
    "Most",
    "Klucz",
    "Kanapka",
    "Wróżka",
    "Piramida",
    "Różdżka",
    "Ser",
    "Szczoteczka do zębów",
    "Zegar",
    "Długopis",
    "Ołówek",
    "Proca",
    "Hantle",
    "Drukarka",
    "Głośnik",
    "Kaktus",
    "Krasnal",
    "Znak",
    "Taksówka",
    "Siekiera",
    "Kamera",
    "Aparat",
    "Widelec",
    "Wiśnia",
    "Awokado",
    "Koparka",
    "Miecz świetlny",
    "Nóż",
    "Pralka",
    "Mikrofalówka",
    "Świeczka",
    "Wodospad",
    "Biblia",
    "Drzewo",
    "Pieniądze",
    "Biustonosz",
    "Majtki",
    "Śmietnik",
    "Ziemia",
    "Kometa",
    "Torebka",
    "Drzwi",
    "Golf",
    "Grabie",
    "Żarówka",
    "Łyżwy",
    "Spodnie",
    "Arbuz",
    "Szachownica",
    "Hulajnoga",
    "Deskorolka",
    "Rower",
    "Statua Wolności",
    "Spadochron",
    "Potwór z Loch Ness",
    "But",
    "Rakieta tenisowa",
    "Ping Pong",
    "Dynamit",
    "Pochodnia",
    "Latarnia morska",
    "Kiełbasa",
    "Skuter wodny",
    "Skuter śnieżny",
    "Snowboard",
    "Łuk",
    "Pistolet",
    "Karabin",
    "Armata",
    "Zamek",
    "Plaża",
    "Antena",
    "Kosmita",
    "Piłka nożna",
    "Fontanna",
    "Okulary przeciwsłoneczne",
    "Pachołek",
    "Titanic",
    "Traktor",
    "Telefon",
    "Kukurydza",
    "Kaseta",
    "Wózek inwalidzki",
    "Okulary",
    "Parasol",
    "Miecz",
    "Ceglana ściana",
    "Pizza",
    "Hamburger",
    "Duch",
    "Jajko",
    "Ogień",
    "Ognisko",
    "Dzwon",
    "Kapelusz",
    "Czapka z daszkiem",
    "Kask",
    "Płot",
    "Donut",
    "Krawat",
    "Czaszka",
    "Młotek",
    "Wędka",
    "Kubek",
    "Butelka",
    "Patelnia",
    "Kieliszek",
    "Pomidor",
    "Papryka",
    "Żołnierz",
    "Czołg",
    "Bomba",
    "Garnek",
    "Grzebień",
    "Wulkan",
    "Dom",
    "Komputer",
    "Książka",
    "Czajnik",
    "Lejek",
    "Łóżko",
    "Lampka",
    "Drabina",
    "Monitor",
    "Telewizor",
    "Laptop",
    "Pomarańcza",
    "Winogron",
    "Marchewka",
    "Ananas",
    "Malina",
    "Statek kosmiczny",
    "Truskawka",
    "Śliwka",
    "Słońce",
    "Chmura",
    "Tęcza",
    "Słuchawki",
    "Zombie",
    "Wiatrak",
    "Kwiatek",
    "Słonecznik",
    "Kupa",
    "Tort",
    "Autobus",
    "Rzeka",
    "Wagonik",
    "Lód",
    "Tory",
    "Śrubokręt",
    "Strzała",
    "Piła",
    "Łom",
    "Dynia",
    "Gitara",
    "Samochód",
    "Motocykl",
    "Samolot",
    "Pociąg",
    "Piorun",
    "Gwiazda",
    "Łopata",
    "Medal",
    "Astronauta",
    "Rakieta",
    "Syrena",
    "Brzoskwinia",
    "Góra",
    "Balon",
    "Pędzel",
    "Wiadro",
    "Krzyż",
    "Wózek sklepowy",
    "Wino",
    "Piwo",
    "Zapałki",
    "Koło",
    "Lasso",
    "Kula dyskotekowa",
    "Anioł",
    "Nintendo Switch",
    "Kostka do gry",
    "Sedes",
    "Gaśnica",
    "Nuta",
    "Kij golfowy",
    "Umywalka",
    "Waga",
    "Człowiek",
    "Puzel",
    "Suszarka do włosów",
    "Okno",
    "Stołek",
    "Krzesło",
    "Trąbka",
    "Skrzypce",
    "Gąbka",
    "Basen",
    "Nożyczki",
    "Banan",
    "Babeczka",
    "Bateria",
    "Łódź podwodna",
    "Helikopter",
    "Łódka",
    "Kość",
    "Kręgiel",
    "Kula do kręgli",
    "Popcorn",
    "Usta",
    "Wtyczka",
    "Radiowóz",
    "Straż pożarna",
    "Ząb",
    "Róża",
    "Flaga Francji",
    "Flaga Polski",
    "Flaga Hiszpanii",
    "Flaga Włoch",
    "Flaga Holandii",
    "Dinozaur",
    "Kura",
    "Świnia",
    "Owca",
    "Jednorożec",
    "Ślimak",
    "Mysz",
    "Kot",
    "Pies",
    "Koń",
    "Ryba",
    "Osioł",
    "Wąż",
    "Dżdżownica",
    "Nietoperz",
    "Kanarek",
    "Rekin",
    "Wieloryb",
    "Delfin",
    "Bocian",
    "Krowa",
    "Pingwin",
    "Lew",
    "Papuga",
    "Zebra",
    "Żyrafa",
    "Skorpion",
    "Rak",
    "Słoń",
    "Koala",
    "Mrówka",
    "Panda",
    "Sowa",
    "Krokodyl",
    "Jeleń",
    "Kaczka",
    "Wilk",
    "Królik",
    "Kangur",
    "Zółw",
    "Żaba",
    "Ośmiornica",
    "Niedźwiedź",
    "Pająk",
    "Mucha",
    "Pszczoła",
    "Motyl",
    "Łabędź",
    "Gęś",
    "Smok",
    "Lis",
    "Lama",
    "Konik morski",
    "Palma",
)